// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"backend/hello-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 你好，世界
				Method:  http.MethodGet,
				Path:    "/hello",
				Handler: helloInfoHandler(serverCtx),
			},
		},
	)
}
