POST http://localhost:8888/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-982002ecb9436180a78303384bad82d9-d85d39b3851fe20d-00
date: Fri, 08 Nov 2024 10:11:48 GMT
content-length: 524
connection: close
###
POST http://localhost:8888/api/refresh-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA5NTA0OTAsImlhdCI6MTczMDc3NzY5MCwidXNlcklEIjoxfQ.OMLwhX9YigvQ7o30xdN3L8uDO0tcsnTlofTPxOZkO4s

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-bf2286c63aa1018822cf5dc92a175e43-8a278c40fda12225-00
date: Tue, 05 Nov 2024 03:37:43 GMT
content-length: 383
connection: close
###
GET http://localhost:8888/api/get-async-routes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzA5NTA0OTAsImlhdCI6MTczMDc3NzY5MCwidXNlcklEIjoxfQ.OMLwhX9YigvQ7o30xdN3L8uDO0tcsnTlofTPxOZkO4s

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-d044cd7d413b644685acff4cea318472-7dd722bffbb32035-00
date: Tue, 05 Nov 2024 06:31:43 GMT
content-length: 656
connection: close
###
GET http://localhost:8888/api/role-menu HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzExNDcxMTgsImlhdCI6MTczMTA2MDcwOCwidXNlcklEIjoxfQ.Hdhup4scZOg8do276H_d6bh-mGCsc50r8tz12R3sxRw

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-e2cecc39535a9faa53002505ba48bd2a-b8b4c25c527b0a5e-00
date: Fri, 08 Nov 2024 10:12:36 GMT
content-length: 33
connection: close