@host=http://localhost:8888
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzIyNjE2OTIsImlhdCI6MTczMjE3NTI4MiwidXNlcklEIjoxfQ.9lBc9CKMY5JF4rwIVtoUQRY4OcsaDVaO5eM_ojVHwoE
###
POST /api/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-4610d66c9389b14d755f6b4c036b933e-0b26c56356bd8fd9-00
date: Thu, 21 Nov 2024 07:48:02 GMT
content-length: 524
connection: close
###
    "password": "admin123"
}
###
POST /api/refresh-token HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-01dd70ba169990a2ec7a2a17be2e7bb4-82f11ca8b2972578-00
date: Tue, 19 Nov 2024 03:26:48 GMT
content-length: 383
connection: close
###
GET http://localhost:8888/api/get-async-routes HTTP/1.1
Authorization: Bearer {{token}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-905bfbfd73103c7a1accd8668d33700d-6210308220e66ff6-00
date: Tue, 19 Nov 2024 03:27:00 GMT
content-length: 947
connection: close
###
POST http://localhost:8888/api/role
Authorization: {{token}}
Content-Type: application/json

{
    "name": "普通角色",
    "code": "common"
}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-830de5c85fda632c0a4d35b32021ae60-3d0a62142a22ed52-00
date: Thu, 21 Nov 2024 07:48:30 GMT
content-length: 203
connection: close
###
GET http://localhost:8888/api/role-menu HTTP/1.1
Authorization: {{token}}

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
traceparent: 00-0c0f33f72e6c21ce33b3fd9a17be3035-1dfa956cbc301f07-00
date: Thu, 21 Nov 2024 07:48:44 GMT
content-length: 466
connection: close